---
domain_keywords:
  - bitcoin
  - free
  - capital
  - trust

domains_whitelist:
  - truehost.co.ke

tlds:
  - xyz
  - uk
  - vip

asns:
  - 16276
  - 174
  - 212317
  - 213230
  - 24940
  - 35540
  - 62563


